### ISSUE TITLE
Duplicate currency symbol

### ISSUE THREAD

**Issue by wolffe** [scottopolis/edd-metrics#32]
Great job with EDD Metrics!

The currency symbol is duplicated on the dashboard page. See attached screenshot.

![caa944cd4fd1a468f909b2b07093b8a6](https://cloud.githubusercontent.com/assets/910240/19031988/40da78ba-894f-11e6-97c0-42cfaf04c5a2.png)

**Comment by Netzberufler** [comment]
The last update made some changes for currency formatting and now uses the default EDD settings, but I'm not able to replicate this particular issue. 

Since payment data is cached with a one hour transient this might just be a caching issue caused by the update. You can also try a different browser which ensures that no old browser cached JavaScript files are used. Are you using the latest version of EDD Metrics?

**Comment by wolffe** [comment]
You are right, it was cached. I checked it now and I only had one currency symbol.
